### PR TITLE
Fixes #1501

### LINKED ISSUE #1501: `pat-select2` unable to load pt-br language file
Image

In Brazilian Portuguese, the file cannot be found because the file URL is incorrect.

Image

Change to: 
`lang = (lang.length > 1) ? `${lang[0]}-${lang[1].toUpperCase()}` : lang[0];`

### PR DESCRIPTION
**Pull request by codeWithPunith**
- [x] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [x] I verified there aren't any other open pull requests for the same change.
- [x] I followed the guidelines in [Contributing to Plone](https://6.docs.plone.org/contributing/index.html).
- [x] I successfully ran code quality checks on my changes locally.
- [x] I successfully ran tests on my changes locally.
- [x] If needed, I added new tests for my changes.
- [x] If needed, I added [documentation](https://6.docs.plone.org/contributing/documentation/index.html) for my changes.
- [x] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #

### CODE REVIEW

**Comment by petschki** [comment]
Hi and thank you for your contribution!

Please read this section carefully https://github.com/plone/mockup/blob/master/README.md#commit-style-guide ... you must not edit CHANGES, because its generated with conventional commits.

And please create an issue which gets fixed by this PR and reference to it with a conventional commit.

**Comment by petschki** [comment]
1. There is already an issue: #1501 ... please reference to it in the pull request description and in your commit message like `fix(pat select2): Fix combined language codes for select2 translations. Fixes #1501` ... you can rename a commit message with `git rebase -i upstream/master` in your local fork. Read the git instructions carefully for this action.
2. Remove the last 2 commits which modify the CHANGELOG ... you can do that within the same rebase above.

File: src/pat/select2/select2.js [hunk 1]
```diff
@@ -111,8 +111,8 @@ export default Base.extend({
             // Don't load "en" which is the default where no separate language file exists.
             if (this.options.language && this.options.language !== "en" && !this.options.language.startsWith("en")) {
                 let lang = this.options.language.split("-");
-                // Fix for country specific languages
-                lang = (lang.length > 1) ? `${lang[0]}-${lang[1]}` : lang[0];        
+                // Fix for country specific languages pt-BR
+                lang = (lang.length > 1) ? `${lang[0]}-${lang[1].toUpperCase()}` : lang[0];
```
Comment (petschki) [inline src/pat/select2/select2.js]: This should only be implemented for the available combined language codes here: https://github.com/ivaynberg/select2/tree/3.5.4 ...

for example, if we have `de-at` or `de-ch` selected as language, we would not get the `de` translations as expected. Please change this to lookup the available combinations from select2.

File: yarn.lock
Comment (petschki) [inline yarn.lock]: Please do not update dependency versions when fixing a bug. This is done in separate maintenance PRs.

**Review by petschki — CHANGES_REQUESTED** [review]

**Comment by petschki** [comment]
One more thing: it would be great if you could do the same changes for the maintenance branch `5.4.x` here ... then it lands in Plone `6.1.x` too ... master branch targets `6.2` only
